app/urls.py
from django.urls import path
from . import views
from .views import (
    EditorDetailView, 
    EditorCreateView,
    EditorUpdateView,
    EditorDeleteView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    taskSubmitRedirect,
    updateArticleOrder,
    ArticleTaskCreateView,
    ArticleTaskDeleteView,
    ArticleTaskUpdateView,
    ImageTaskCreateView,
    ImageTaskDeleteView,
    ImageTaskUpdateView,
    ImageTaskSubmitView,
    TextTaskCreateView,
    TextTaskDeleteView,
    TextTaskUpdateView,
    TextTaskSubmitView,
    AdTaskCreateView,
    AdTaskDeleteView,
    AdTaskUpdateView,
    AdTaskSubmitView,
    TypoTaskCreateView,
    TypoTaskDeleteView,
    TypoTaskUpdateView
)

app_name = "app"
urlpatterns = [
    path("", views.index, name="index"),
    path("newspaper/<int:pk>/", EditorDetailView.as_view(), name='editor'),
    path("newspaper/new/", EditorCreateView.as_view(), name='editor-create'),
    path("newspaper/<int:pk>/update/", EditorUpdateView.as_view(), name='editor-update'),
    path("newspaper/<int:pk>/delete/", EditorDeleteView.as_view(), name='editor-delete'),

    path("newspaper/<int:newspaper_id>/newarticle/", ArticleCreateView.as_view(), name='article-create'),
    path("newspaper/<int:newspaper_id>/article/<int:pk>/update", ArticleUpdateView.as_view(), name='article-update'),
    path("newspaper/<int:newspaper_id>/article/<int:pk>/delete", ArticleDeleteView.as_view(), name='article-delete'),

    path("newspaper/<int:newspaper_id>/newarticletask/", ArticleTaskCreateView.as_view(), name='articletask-create'),
    path("newspaper/<int:newspaper_id>/articletask/<int:pk>/delete", ArticleTaskDeleteView.as_view(), name='articletask-delete'),
    path("newspaper/<int:newspaper_id>/articletask/<int:pk>/update", ArticleTaskUpdateView.as_view(), name='articletask-update'),

    path("articletask/<int:articletask_id>/subtask/<int:pk>/submit", views.taskSubmitRedirect, name="subtask-submit"),

    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/newimagetask", ImageTaskCreateView.as_view(), name='imagetask-create'),
    path("articletask/<int:articletask_id>/imagetask/<int:pk>/submit", ImageTaskSubmitView.as_view(), name='imagetask-submit'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/imagetask/<int:pk>/delete", ImageTaskDeleteView.as_view(), name='imagetask-delete'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/imagetask/<int:pk>/update", ImageTaskUpdateView.as_view(), name='imagetask-update'),

    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/newtexttask", TextTaskCreateView.as_view(), name='texttask-create'),
    path("articletask/<int:articletask_id>/texttask/<int:pk>/submit", TextTaskSubmitView.as_view(), name='texttask-submit'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/texttask/<int:pk>/delete", TextTaskDeleteView.as_view(), name='texttask-delete'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/texttask/<int:pk>/update", TextTaskUpdateView.as_view(), name='texttask-update'),

    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/newadtask", AdTaskCreateView.as_view(), name='adtask-create'),
    path("articletask/<int:articletask_id>/adtask/<int:pk>/submit", AdTaskSubmitView.as_view(), name='adtask-submit'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/adtask/<int:pk>/delete", AdTaskDeleteView.as_view(), name='adtask-delete'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/adtask/<int:pk>/update", AdTaskUpdateView.as_view(), name='adtask-update'),

    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/newtypotask", TypoTaskCreateView.as_view(), name='typotask-create'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/typotask/<int:pk>/delete", TypoTaskDeleteView.as_view(), name='typotask-delete'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/typotask/<int:pk>/update", TypoTaskUpdateView.as_view(), name='typotask-update'),

    path("newspaper/ajax/article_order", updateArticleOrder, name='article-order-update')
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users import views as user_views
from app import views as app_views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache

from ckeditor_uploader import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('add_user/', user_views.add_user, name='add-user'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('app.urls')),
    path('ckeditor/upload', login_required(views.upload), name='ckeditor_upload'),
    path('ckeditor/browse', never_cache(login_required(views.browse)), name='ckeditor_browse'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

from model_utils import FieldTracker


class Newspaper(models.Model):
    title = models.CharField(max_length=100)
    date_posted = models.DateField(default=timezone.now)

    COLUMN_CHOISES = (
        ('2', 2),
        ('3', 3),
        ('4', 4),
        ('5', 5),
    )

    columns = models.CharField(max_length=1, choices=COLUMN_CHOISES, default=3)

    FORMAT_CHOISES = {
        ('broadsheet', 'Broadsheet - 600 x 750 mm (23.5" x 29.5")'),
        ('berliner', 'Berliner - 315 x 470 mm (12.4" x 18.5")'),
        ('tabloid', 'Tabloid - 280 x 430 mm (11.0" x 16.9")')
    }

    page_size = models.CharField(max_length=100, choices=FORMAT_CHOISES, default='berliner')

    # If the User gets deleted, the newspaper also deletes
    # Foreign key provides many-to-one relationship (User can have many newspapers created)
    author = models.ForeignKey(User, on_delete=models.CASCADE) 

    def __str__(self):
        return "'{}' created by {}".format(self.title, self.author)

    def get_absolute_url(self):
        return reverse('profile')
        # return reverse('editor', kwargs={'pk': self.pk})
    

class ArticleTask(models.Model):
    date_created = models.DateField(default=timezone.now)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    newspaper = models.ForeignKey(Newspaper, on_delete=models.CASCADE, default=0)
    

    STATUS_CHOISES = (
        ('in progress', 'in progress'),
        ('archived', 'archived'),
    )

    status = models.CharField(max_length=100, choices=STATUS_CHOISES, default='in progress')

    def __str__(self):
        return "'{}' article task owned by {}".format(self.title, self.newspaper.author)


class Article(models.Model):
    title = models.CharField(max_length=100)
    # content = RichTextField(config_name='custom_ckeditor', blank=True, null=True)
    content = RichTextUploadingField(config_name='custom_ckeditor', blank=True)
    author = models.CharField(max_length=50)
    date_created = models.DateField(default=timezone.now)
    newspaper = models.ForeignKey(Newspaper, on_delete=models.CASCADE)
    order = models.IntegerField(default=1000, null=True)

    articletask = models.OneToOneField(ArticleTask, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return "'{}' written by {}".format(self.title, self.author)


class BaseTask(models.Model):
    assignee = models.ForeignKey(User, on_delete=models.CASCADE)
    articletask = models.ForeignKey(ArticleTask, on_delete=CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    STATUS_CHOISES = (
        ('in progress', 'in progress'),
        ('awaiting review', 'awaiting review'),
        ('confirmed', 'confirmed'),
    )

    status = models.CharField(max_length=100, choices=STATUS_CHOISES, default='in progress')

    # class Meta:
    #     abstract=True

    def __str__(self):
        return "'{}' subtask owned by {} and assigned to".format(self.title, self.articletask.newspaper.author)


class ImageTask(BaseTask):
    # assignee = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': "Illustrator"})
    image = RichTextUploadingField(config_name='custom_ckeditor', blank=True, null=True)
    tracker = FieldTracker()


class TextTask(BaseTask):
    # assignee = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': "Author"})
    article_title = models.CharField(max_length=100, blank=True)
    content = RichTextUploadingField(config_name='custom_ckeditor')
    author = models.CharField(max_length=50, blank=True)
    date_created = models.DateField(default=timezone.now)
    tracker = FieldTracker()


class AdTask(BaseTask):
    # assignee = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': "Advertisement designer"})
    ad_title = models.CharField(max_length=100, blank=True)
    content = RichTextUploadingField(config_name='custom_ckeditor', blank=True, null=True)
    tracker = FieldTracker()


class TypoTask(BaseTask):
    # assignee = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': "Head of typography"})
    pass

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    # Removed for AWS support
    # # Resize large images
    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)

    #     img = Image.open(self.image.path)

    #     if img.height > 300 or img.width > 300:
    #         output_size = (300, 300)
    #         img.thumbnail(output_size)
    #         img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from .models import Profile
from django.contrib.auth.forms import UserCreationForm


# ModelForm allows to create form that will work sith 
# specific database model
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']


class UserForm(UserCreationForm):
    # group = forms.Select(choices=[
    #     ('simple_user', 'Simple user'),
    #     ('copy_editor', 'Copy editor')
    # ])

    group = forms.ModelChoiceField(queryset=Group.objects.all(), required=True)

    class Meta:
        model = User
        fields = ('username', 'group', 'password1' ,'password2' )

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, ProfileUpdateForm, UserForm
from django.contrib.auth.models import Group
from .decorators import group_required

def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name=form.cleaned_data.get('group'))
            user.groups.add(group)
            username = form.cleaned_data.get('username')
            messages.success(request, f'{username}, your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserForm()

    return render(request, 'users/register.html', context={'form': form, 'title': 'sign up'})


@login_required
@group_required('Copy editor')
def add_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            group = Group.objects.get(name=form.cleaned_data.get('group'))
            user.groups.add(group)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account with username "{username}" and role "{group}" has been created! You are now able to give it to your new worker!')
            return redirect('profile')
    else:
        form = UserForm()

    return render(request, 'users/register.html', context={'form': form, 'title': 'sign up'})


@login_required
def profile(request):
    # If user want to change smth
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        # Check forms for correctness
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            # Say user that all things are succedeed and show fresh profile
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    if isUserInGroup(request.user, "Default user") or isUserInGroup(request.user, "Copy editor"):
        return render(request, 'users/profile.html', context)
    else:
        return render(request, 'users/profile_workers.html', context)


def isUserInGroup(user, groupname):
    return user.groups.filter(name=groupname).exists()

users/templates/users/login.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_head %}
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
{% endblock extra_head %}



{% block content %}

    <div class="content-section">
        <form id="main-form" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <img class="mb-4" src="{% static 'images/newspaper_logo.png' %}" alt="" width="100" height="100" id="image_logo">
                <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}

                {{ form|crispy  }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-primary" type="submit">Login</button>
            </div>
        </form> 
        <div class="pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up</a>
            </small>
        </div>
    </div>
{% endblock content %}

{% block script %}
<script>
    (function () {
        document.forms["main-form"].getElementsByTagName("input")[1].placeholder="Username";
        document.forms["main-form"].getElementsByTagName("input")[2].placeholder="Password";
    })();
</script>
{% endblock script %}

users/templates/users/logout.html
{% extends "app/base.html" %}
{% load static %}

{% block extra_head %}
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
{% endblock extra_head %}

{% block content %}
    <div class="content-section"
        <h2 class="h3 mb-3 font-weight-normal">You have been logged out</h2>
        <div class="pt-3">
            <small class="text-muted">
                <a class="ml-2" href="{% url 'login' %}">Log In Again</a>
                <a class="ml-2" href="{% url 'app:index' %}">Home</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_head %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock extra_head %}

{% block content %}

    <div class="h-100 container hide-scrollbar"  style="overflow-y: scroll;">

        <!-- Header - where newspaper editor placed -->
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-center align-items-center">
                <a class="blog-header-logo text-dark" href="{% url 'app:index' %}">Newspaper Editor</a>
            </div>
        </header>


        <!-- Buttons of header -->
        <div class="nav-scroller py-1 mb-4">
            <nav class="nav d-flex justify-content-center">
            <a class="p-2 text-muted" href="{% url 'app:index' %}">Home</a>
            <a class="p-2 text-muted" href="{% url 'logout' %}">Logout</a>
            <a class="p-2 text-muted" href="{% url 'register' %}">Sign Up</a>
            </nav>
        </div>

        <!-- Profile card -->
        <!-- https://bbbootstrap.com/snippets/bootstrap-sidebar-user-profile-62301382 -->
        <div class="row mt-3">
            <div class="col-md-4 mr-5">
                <div class="card p-3">
                    <div class="d-flex align-items-center">
                        <div class="image"> 
                            <img src="{{ user.profile.image.url }}" class="rounded" width="250" height="250"> 
                            <div class="button mt-2 d-flex flex-row align-items-center"> 
                                <button class="btn btn-sm btn-outline-primary w-100" onclick="showEdit()">Edit profile</button>
                            </div>
                        </div>

                        <div class="ml-3 w-100">

                            {% if user.get_full_name != '' %}
                                <h5 class="mt-0">{{ user.get_full_name }}</h5> 
                            {% else %}
                                <h5 class="mt-0">{{ user.username }}</h5> 
                            {% endif %}

                            <h6 class="mb-3 mt-0">{{ user.groups.all.0 }}</h6> 

                            <div class="p-2 mt-2 bg-primary d-flex justify-content-center rounded text-white stats">
                                <div class="d-flex flex-column"> <span class="articles">Newspapers</span> <span class="number1">{{ user.newspaper_set.count }}</span></div>
                            </div>

                            <div class="button mt-2 d-flex flex-row align-items-center"> 
                                <a class="btn btn-sm btn-outline-success w-100" href="{% url 'app:editor-create' %}">Create Newspaper</a>
                            </div>

                            <div class="button mt-2 d-flex flex-row align-items-center"> 
                                <a class="btn btn-sm btn-outline-primary w-100" href="{% url 'add-user' %}">Add user</a>
                            </div>
                        </div>
                    </div>

                    <!-- Display message that account was updated -->
                    {% if messages %}
                        {% for message in messages %}
                            <div class="mt-4 alert alert-{{ message.tags }}">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <!-- Edit user preferenes form (hidden by default) -->
                    <div class="d-none align-items-center mt-4" id="editProfileDiv">
                        <div class="w-100">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    {{ u_form|crispy  }}
                                    {{ p_form|crispy  }}
                                </fieldset>

                                <div class="button d-flex flex-row align-items-center"> <button class="btn btn-sm btn-outline-primary w-100" type="submit">Update</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


            <!-- Users newspapers cards -->
            <div class="col-md-7 mb-5">
                {% if user.newspaper_set.count == 0 %}
                    <div class="nsp-card p-3 mb-3">
                        <div class="d-flex align-items-center">
                            <div class="ml-3 w-100">
                                <p class="mt-0">You don't have any newspapers yet</p> 
                            </div>
                        </div>
                    </div>
                {% else %}
                    {% for newspaper in user.newspaper_set.all %}
                            <div class="nsp-card p-3 mb-3">
                                <div class="d-flex align-items-center">
                                    <div class="w-100">
                                        <h5 class="mb-3 mt-0">{{ newspaper.title }}</h5> 
                                        
                                        <div class="p-2 mt-2 bg-primary d-flex justify-content-center rounded text-white stats">
                                            <div class="d-flex flex-column ml-2 mr-2"> <span class="articles">Articles</span> <span class="number1">{{ newspaper.article_set.count }}</span></div>
                                            <!-- <div class="d-flex flex-column ml-2 mr-2"> <span class="articles">Pages</span> <span class="number1">5</span></div> -->
                                        </div>

                                        <div class="button mt-2 d-flex flex-row align-items-center"> 
                                            <a class="btn btn-sm btn-outline-primary w-100 mr-1" href="{% url 'app:editor' newspaper.id %}">Open newspaper</a>
                                            <a class="btn btn-sm btn-outline-primary w-100 mr-1" href="{% url 'app:article-create' newspaper.id %}">Add article</a>
                                            <a class="btn btn-sm btn-outline-primary w-100 mr-1" href="{% url 'app:editor-update' newspaper.id %}">Edit parameters</a>
                                            <a class="btn btn-sm btn-outline-danger w-100" href="{% url 'app:editor-delete' newspaper.id %}">Delete newspaper</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>

        
        <!-- Footer with credentials -->
        <div class="row justify-content-center">
            <footer class="footer">
                <p class="mb-0">Newspaper editor app made for NSU Software Development course</p>
                <p class="mb-0">Created by Aleksandr Ushaev and Vladislav Nikiforov</p>
            </footer>
        </div>
    </div>
{% endblock content %}

{% block script %}
    <script>
        function showEdit() {
            $("#editProfileDiv").addClass("d-flex").removeClass("d-none");
        }
    </script>
{% endblock script %}

users/templates/users/profile_workers.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_head %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock extra_head %}

{% block content %}

    <div class="h-100 container hide-scrollbar"  style="overflow-y: scroll;">

        <!-- Header - where newspaper editor placed -->
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-center align-items-center">
                <a class="blog-header-logo text-dark" href="{% url 'app:index' %}">Newspaper Editor</a>
            </div>
        </header>


        <!-- Buttons of header -->
        <div class="nav-scroller py-1 mb-4">
            <nav class="nav d-flex justify-content-center">
            <a class="p-2 text-muted" href="{% url 'app:index' %}">Home</a>
            <a class="p-2 text-muted" href="{% url 'logout' %}">Logout</a>
            <a class="p-2 text-muted" href="{% url 'register' %}">Sign Up</a>
            </nav>
        </div>

        <!-- Profile card -->
        <!-- https://bbbootstrap.com/snippets/bootstrap-sidebar-user-profile-62301382 -->
        <div class="row mt-3">
            <div class="col-md-4 mr-5">
                <div class="card p-3">
                    <div class="d-flex align-items-center">
                        <div class="image"> 
                            <img src="{{ user.profile.image.url }}" class="rounded" width="250" height="250"> 
                            <div class="button mt-2 d-flex flex-row align-items-center"> 
                                <button class="btn btn-sm btn-outline-primary w-100" onclick="showEdit()">Edit profile</button>
                            </div>
                        </div>

                        <div class="ml-3 w-100">

                            {% if user.get_full_name != '' %}
                                <h5 class="mt-0">{{ user.get_full_name }}</h5> 
                            {% else %}
                                <h5 class="mt-0">{{ user.username }}</h5> 
                            {% endif %}

                            <h6 class="mb-3 mt-0">{{ user.groups.all.0 }}</h6> 

                            <div class="p-2 mt-2 bg-primary d-flex justify-content-center rounded text-white stats">
                                <div class="d-flex flex-column"> <span class="articles">Assigned tasks</span> <span class="number1">{{ user.basetask_set.count }}</span></div>
                            </div>
                        </div>
                    </div>

                    <!-- Display message that account was updated -->
                    {% if messages %}
                        {% for message in messages %}
                            <div class="mt-4 alert alert-{{ message.tags }}">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}

                    <!-- Edit user preferenes form (hidden by default) -->
                    <div class="d-none align-items-center mt-4" id="editProfileDiv">
                        <div class="w-100">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    {{ u_form|crispy  }}
                                    {{ p_form|crispy  }}
                                </fieldset>

                                <div class="button d-flex flex-row align-items-center"> <button class="btn btn-sm btn-outline-primary w-100" type="submit">Update</button></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>


            <!-- Users newspapers cards -->
            <div class="col-md-7 mb-5">
                {% if user.basetask_set.count == 0 %}
                    <div class="nsp-card p-3 mb-3">
                        <div class="d-flex align-items-center">
                            <div class="ml-3 w-100">
                                <p class="mt-0">You don't have any newspapers yet</p> 
                            </div>
                        </div>
                    </div>
                {% else %}
                    {% for task in user.basetask_set.all %}
                        {% if forloop.counter0|divisibleby:2 %}
                            <div class="row">
                        {% endif %}
                            <div class="col-sm">
                                    <div class="nsp-card p-3 mb-3">
                                        <div class="d-flex align-items-center">
                                            <div class="w-100">
                                                <h5 class="mt-0">{{ task.title }}</h5>
                                                <p class="mt-0">{{ task.status }}</p>
                                                <div class="button mt-2 d-flex flex-row align-items-center">
                                                    <!-- <a class="btn btn-sm btn-outline-primary w-100 mr-1" href="{% url 'app:imagetask-submit' articletask_id=task.articletask.id pk=task.id %}">Open task</a> -->
                                                    <a class="btn btn-sm btn-outline-primary w-100 mr-1" href="{% url 'app:subtask-submit' articletask_id=task.articletask.id pk=task.id %}">Open task</a>

                                                    <a class="btn btn-sm btn-outline-danger w-100" href="">Delete task</a>
                                                </div>
                                            </div>
                                        </div>
                            </div>
                        {% if forloop.counter|divisibleby:2 %}
                            </div>
                        {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        {% if user.basetask_set.count|length|divisibleby:2 %}
            </div>
        {% endif %}
    </div>
        <!-- Footer with credentials -->
        <div class="row justify-content-center">
            <footer class="footer">
                <p class="mb-0">Newspaper editor app made for NSU Software Development course</p>
                <p class="mb-0">Created by Aleksandr Ushaev and Vladislav Nikiforov</p>
            </footer>
        </div>
    </div>
{% endblock content %}

{% block script %}
    <script>
        function showEdit() {
            $("#editProfileDiv").addClass("d-flex").removeClass("d-none");
        }
    </script>
{% endblock script %}