app/urls.py
from django.urls import path
from . import views
from .views import (
    EditorDetailView, 
    EditorCreateView,
    EditorUpdateView,
    EditorDeleteView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    taskSubmitRedirect,
    updateArticleOrder,
    ArticleTaskCreateView,
    ArticleTaskDeleteView,
    ArticleTaskUpdateView,
    ImageTaskCreateView,
    ImageTaskDeleteView,
    ImageTaskUpdateView,
    ImageTaskSubmitView,
    TextTaskCreateView,
    TextTaskDeleteView,
    TextTaskUpdateView,
    TextTaskSubmitView,
    AdTaskCreateView,
    AdTaskDeleteView,
    AdTaskUpdateView,
    AdTaskSubmitView,
    TypoTaskCreateView,
    TypoTaskDeleteView,
    TypoTaskUpdateView
)

app_name = "app"
urlpatterns = [
    path("", views.index, name="index"),
    path("newspaper/<int:pk>/", EditorDetailView.as_view(), name='editor'),
    path("newspaper/new/", EditorCreateView.as_view(), name='editor-create'),
    path("newspaper/<int:pk>/update/", EditorUpdateView.as_view(), name='editor-update'),
    path("newspaper/<int:pk>/delete/", EditorDeleteView.as_view(), name='editor-delete'),

    path("newspaper/<int:newspaper_id>/newarticle/", ArticleCreateView.as_view(), name='article-create'),
    path("newspaper/<int:newspaper_id>/article/<int:pk>/update", ArticleUpdateView.as_view(), name='article-update'),
    path("newspaper/<int:newspaper_id>/article/<int:pk>/delete", ArticleDeleteView.as_view(), name='article-delete'),

    path("newspaper/<int:newspaper_id>/newarticletask/", ArticleTaskCreateView.as_view(), name='articletask-create'),
    path("newspaper/<int:newspaper_id>/articletask/<int:pk>/delete", ArticleTaskDeleteView.as_view(), name='articletask-delete'),
    path("newspaper/<int:newspaper_id>/articletask/<int:pk>/update", ArticleTaskUpdateView.as_view(), name='articletask-update'),

    path("articletask/<int:articletask_id>/subtask/<int:pk>/submit", views.taskSubmitRedirect, name="subtask-submit"),

    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/newimagetask", ImageTaskCreateView.as_view(), name='imagetask-create'),
    path("articletask/<int:articletask_id>/imagetask/<int:pk>/submit", ImageTaskSubmitView.as_view(), name='imagetask-submit'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/imagetask/<int:pk>/delete", ImageTaskDeleteView.as_view(), name='imagetask-delete'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/imagetask/<int:pk>/update", ImageTaskUpdateView.as_view(), name='imagetask-update'),

    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/newtexttask", TextTaskCreateView.as_view(), name='texttask-create'),
    path("articletask/<int:articletask_id>/texttask/<int:pk>/submit", TextTaskSubmitView.as_view(), name='texttask-submit'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/texttask/<int:pk>/delete", TextTaskDeleteView.as_view(), name='texttask-delete'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/texttask/<int:pk>/update", TextTaskUpdateView.as_view(), name='texttask-update'),

    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/newadtask", AdTaskCreateView.as_view(), name='adtask-create'),
    path("articletask/<int:articletask_id>/adtask/<int:pk>/submit", AdTaskSubmitView.as_view(), name='adtask-submit'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/adtask/<int:pk>/delete", AdTaskDeleteView.as_view(), name='adtask-delete'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/adtask/<int:pk>/update", AdTaskUpdateView.as_view(), name='adtask-update'),

    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/newtypotask", TypoTaskCreateView.as_view(), name='typotask-create'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/typotask/<int:pk>/delete", TypoTaskDeleteView.as_view(), name='typotask-delete'),
    path("newspaper/<int:newspaper_id>/articletask/<int:articletask_id>/typotask/<int:pk>/update", TypoTaskUpdateView.as_view(), name='typotask-update'),

    path("newspaper/ajax/article_order", updateArticleOrder, name='article-order-update')
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users import views as user_views
from app import views as app_views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache

from ckeditor_uploader import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('add_user/', user_views.add_user, name='add-user'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('app.urls')),
    path('ckeditor/upload', login_required(views.upload), name='ckeditor_upload'),
    path('ckeditor/browse', never_cache(login_required(views.browse)), name='ckeditor_browse'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

from model_utils import FieldTracker


class Newspaper(models.Model):
    title = models.CharField(max_length=100)
    date_posted = models.DateField(default=timezone.now)

    COLUMN_CHOISES = (
        ('2', 2),
        ('3', 3),
        ('4', 4),
        ('5', 5),
    )

    columns = models.CharField(max_length=1, choices=COLUMN_CHOISES, default=3)

    FORMAT_CHOISES = {
        ('broadsheet', 'Broadsheet - 600 x 750 mm (23.5" x 29.5")'),
        ('berliner', 'Berliner - 315 x 470 mm (12.4" x 18.5")'),
        ('tabloid', 'Tabloid - 280 x 430 mm (11.0" x 16.9")')
    }

    page_size = models.CharField(max_length=100, choices=FORMAT_CHOISES, default='berliner')

    # If the User gets deleted, the newspaper also deletes
    # Foreign key provides many-to-one relationship (User can have many newspapers created)
    author = models.ForeignKey(User, on_delete=models.CASCADE) 

    def __str__(self):
        return "'{}' created by {}".format(self.title, self.author)

    def get_absolute_url(self):
        return reverse('profile')
        # return reverse('editor', kwargs={'pk': self.pk})
    

class ArticleTask(models.Model):
    date_created = models.DateField(default=timezone.now)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    newspaper = models.ForeignKey(Newspaper, on_delete=models.CASCADE, default=0)
    

    STATUS_CHOISES = (
        ('in progress', 'in progress'),
        ('archived', 'archived'),
    )

    status = models.CharField(max_length=100, choices=STATUS_CHOISES, default='in progress')

    def __str__(self):
        return "'{}' article task owned by {}".format(self.title, self.newspaper.author)


class Article(models.Model):
    title = models.CharField(max_length=100)
    # content = RichTextField(config_name='custom_ckeditor', blank=True, null=True)
    content = RichTextUploadingField(config_name='custom_ckeditor', blank=True)
    author = models.CharField(max_length=50)
    date_created = models.DateField(default=timezone.now)
    newspaper = models.ForeignKey(Newspaper, on_delete=models.CASCADE)
    order = models.IntegerField(default=1000, null=True)

    articletask = models.OneToOneField(ArticleTask, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return "'{}' written by {}".format(self.title, self.author)


class BaseTask(models.Model):
    assignee = models.ForeignKey(User, on_delete=models.CASCADE)
    articletask = models.ForeignKey(ArticleTask, on_delete=CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    STATUS_CHOISES = (
        ('in progress', 'in progress'),
        ('awaiting review', 'awaiting review'),
        ('confirmed', 'confirmed'),
    )

    status = models.CharField(max_length=100, choices=STATUS_CHOISES, default='in progress')

    # class Meta:
    #     abstract=True

    def __str__(self):
        return "'{}' subtask owned by {} and assigned to".format(self.title, self.articletask.newspaper.author)


class ImageTask(BaseTask):
    # assignee = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': "Illustrator"})
    image = RichTextUploadingField(config_name='custom_ckeditor', blank=True, null=True)
    tracker = FieldTracker()


class TextTask(BaseTask):
    # assignee = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': "Author"})
    article_title = models.CharField(max_length=100, blank=True)
    content = RichTextUploadingField(config_name='custom_ckeditor')
    author = models.CharField(max_length=50, blank=True)
    date_created = models.DateField(default=timezone.now)
    tracker = FieldTracker()


class AdTask(BaseTask):
    # assignee = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': "Advertisement designer"})
    ad_title = models.CharField(max_length=100, blank=True)
    content = RichTextUploadingField(config_name='custom_ckeditor', blank=True, null=True)
    tracker = FieldTracker()


class TypoTask(BaseTask):
    # assignee = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': "Head of typography"})
    pass

app/templates/app/adtask_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_head %}
    <link href="{% static 'css/article.css' %}" rel="stylesheet">
{% endblock extra_head %}

{% block content %}
    <div class="content-section wide mt-5">
        <form id="main-form" method="POST">
            {% csrf_token %}
            <fieldset class="form-group wide">
                <img class="mb-4" src="{% static 'images/newspaper_logo.png' %}" alt="" width="100" height="100" id="image_logo">
                <h1 class="h3 mb-3 font-weight-normal">Create new ad subtask</h1>
                {{ form.media  }}
                {{ form|crispy  }}
            </fieldset>
            <div class="mt-3 form-group">
                <input class="btn btn-outline-primary w-50 mb-2" type="submit" name="to_profile" value='Create'>
                <a class="btn btn-outline-secondary w-50 mb-3" href="{% url 'profile' %}">Cancel</a>
            </div>
        </form> 
    </div>
{% endblock content %}

{% block script %}
<script>
    (function () {
        document.forms["main-form"].getElementsByTagName("input")[1].placeholder="Title";
        document.forms["main-form"].getElementsByTagName("textarea")[0].placeholder="Description";
    })();
</script>
{% endblock script %}

app/templates/app/editor copy.html
{% extends "app/base.html" %}
{% load static %}

{% block extra_head %}
    <script src="{% static 'bundles/columnizer/src/jquery.js' %}"></script>
    <script src="{% static 'bundles/columnizer/src/jquery.columnizer.min.js' %}" type="text/javascript" charset="utf-8"></script>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" >
{% endblock extra_head %}


{% block content %}

    <!-- TODO navbars from bootstrap -->
    <!-- Toolbar - top navbar -->
    <div class="topnav">
        <div class="d-flex justify-content-center" style="margin-left: 200px;">

            <a href="{% url 'app:index' %}">Home</a>

            {% if user.get_full_name != '' %}
                <a href="{% url 'profile' %}">{{ user.get_full_name }}</a>
            {% else %}
                <a href="{% url 'profile' %}">{{ user.username }}</a>
            {% endif %}

            <a href="{% url 'logout' %}">Logout</a>
            <a href="{% url 'app:article-create' object.id %}" style="background-color: cadetblue;">Add article</a>
        </div>
    </div>


    <!-- Table of contents - left navbar -->
    <div class="sidenav">
        <hr>
        <div class="sidebar-heading">{{ object.title }}</div>
        <hr>

        {% for article in object.article_set.all %}
            <a href="#">{{ article.title }}</a>
            <hr>
        {% endfor %}

    </div>

    
    <!-- Page content -->
    <div class="main">

        <!-- Loading spinner while newspaper generation happens -->
        <div class="d-flex justify-content-center">
            <div id='loading' class="spinner-grow" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>

        <!-- Editor div - where newspaper placed -->
        <div id='editor' style="visibility: hidden; transform: scale(0.8);">

            <!-- Page template. Probably should be in other file -->
            <page size="A5" id="page_template">
                <div class='header'>
                    {{ object.title }}
                    <hr>
                </div>
                <div class='content'></div>
                <div class='footer'>
                    <hr>
                    <span>Page: </span>
                    {{ object.date_posted }}
                </div>
            </page>

            <!-- Info which columnizer use to generate newspaper pages -->
            <div id="newsletterContent">

                {% for article in object.article_set.all %}
                    <h1>{{ article.title }}</h1>
                    <p><i>By {{ article.author }} at {{ article.date_created }}</i></p>
                    <p>{{ article.content|safe }}</p>
                {% endfor %}


            </div>
        </div>
    </div>


    <!-- Page scale buttons -->
    <div style ="position: fixed; bottom: 15px; right:15px;">
        <a id="zoomOutButton" class="btn btn-secondary btn-circle""><i class="fa fa-minus" aria-hidden="true"></i></i></a>
        <a id="zoomInButton" class="btn btn-secondary btn-circle"><i class="fa fa-plus" aria-hidden="true"></i></a>
    </div>

   
{% endblock content %}

{% block script %}

    <script>
        var zoom = 1;
        var zoomStep = 0.2;

        document.getElementById("zoomInButton").addEventListener("click", function() {
          zoom += zoomStep;
          document.getElementById("editor").style.transform = "scale(" + zoom + ")";
        });
        document.getElementById("zoomOutButton").addEventListener("click", function() {
          if (zoom > zoomStep) {
            zoom -= zoomStep;
            document.getElementById("editor").style.transform = "scale(" + zoom + ")";
          }
        });
    </script>

    <script>
        $(function() {
            var content_height = 2070; // the height of the content, discluding the header/footer
            var page = 1; // the beginning page number to show in the footer
            function buildNewsletter() {

                if ($('#newsletterContent').contents().length > 0) {
                    // when we need to add a new page, use a jq object for a template
                    // or use a long HTML string, whatever your preference
                    $page = $("#page_template").clone().addClass("page").css("display", "block");

                    // fun stuff, like adding page numbers to the footer
                    $page.find(".footer span").append(page);
                    $("#editor").append($page);
                    page++;

                    // here is the columnizer magic
                    $('#newsletterContent').columnize({
                        columns: 4,
                        target: ".page:last .content",
                        overflow: {
                            height: content_height,
                            id: "#newsletterContent",
                            doneFunc: function() {
                                console.log("done with page");
                                buildNewsletter();
                            }
                        }
                    });
                }
                $('#loading').hide();
                $('#editor').css("visibility", "visible");
            }

            setTimeout(buildNewsletter, 1000);
        });
    </script>
{% endblock script %}

app/templates/app/editor.html
{% extends "app/base.html" %}
{% load static %}

{% block extra_head %}
    <script src="{% static 'bundles/columnizer/src/jquery.js' %}"></script>
    <script src="{% static 'bundles/columnizer/src/jquery.columnizer.min.js' %}" type="text/javascript" charset="utf-8"></script>
    <link href="{% static 'css/editor.css' %}" rel="stylesheet" >

    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">  

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
    
{% endblock extra_head %}

{% block body_class %}
{% endblock %}

{% block content %}

<div class="wrapper">

    <!-- Sidebar -->
    <nav id="sidebar">

        <!-- Newspaper name -->
        <div class="sidebar-header">
            <h3>{{ object.title }}</h3>
        </div>

        <ul class="list-unstyled components">
            <!-- User profile -->
            <li >
                {% if user.get_full_name != '' %}
                    <a href="{% url 'profile' %}">{{ user.get_full_name }}</a>
                {% else %}
                    <a href="{% url 'profile' %}">{{ user.username }}</a> 
                {% endif %}
            </li>

            <!-- Articles -->
            <li>
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Articles</a>
                <ul class="collapse list-unstyled articles" id="homeSubmenu">

                    {% for article in object.article_set.all %}

                        <ul class="navbar-nav draggable article-item" draggable="true" id='{{ article.id }}'>
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="#" data-toggle="dropdown">{{ article.title }}</a>
                                <p id="article-id" style="display: none;">{{ article.id }}</p>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'app:article-update' object.id article.id %}">Edit article</a></li>
                                    <li><a class="dropdown-item" href="{% url 'app:article-delete' object.id article.id %}">Delete article</a></li>
                                </ul>
                            </li>
                        </ul>
                    {% endfor %}

                </ul>
            </li>

            <li>
                <a href="{% url 'app:editor-update' object.id %}">Edit newspaper parameters</a>
            </li>

        </ul>

        <!-- Add article button -->
        <ul class="list-unstyled CTAs">
            <li>
                <a href="{% url 'app:article-create' object.id %}" class="btn btn-outline-secondary mb-2">Add article</a>
            </li>
            <li>
                <a class="btn btn-outline-secondary" id="reload-btn" onClick="window.location.href=window.location.href">Reload newspaper</a>
            </li>
        </ul>

    </nav>

    <!-- Page Content -->
    <div id="content">

        <!-- Collapse button -->
        <nav style="position: fixed; z-index: 700;">
            <button type="button" id="sidebarCollapse" class="collapseButton">
                <i class="fas fa-align-left"></i>
            </button>
        </nav>

        <!-- Page content -->
        <!-- Loading spinner while newspaper generation happens -->
        <div class="d-flex justify-content-center">
            <div id='loading' class="spinner-grow" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>

        <!-- Editor div - where newspaper placed -->
        <div class="" id='editor' style="visibility: hidden; transform: scale(0.8);">

            <!-- Page template. Probably should be in other file -->
            <page size="{{ object.page_size }}" id="page_template">
                <div class='header'>
                    {{ object.title }}
                    <hr size="{{ object.page_size }}">
                </div>
                <div class='content'></div>
                <div class='footer'>
                    <hr size="{{ object.page_size }}">
                    <span>Page: </span>
                    <!-- {{ object.date_posted }} -->
                </div>
            </page>

            <!-- Info which columnizer use to generate newspaper pages -->
            <div id="newsletterContent">

                {% for article in object.article_set.all %}
                    <h1>{{ article.title }}</h1>
                    <p><i>By {{ article.author }} at {{ article.date_created }}</i></p>
                    <p>{{ article.content|safe }}</p>
                {% endfor %}

            </div>
        </div>

        <!-- Page scale buttons -->
        <div style ="position: fixed; bottom: 15px; right:15px;">
            <a id="zoomOutButton" class="btn btn-outline-secondary btn-circle""><i class="fa fa-minus" aria-hidden="true"></i></i></a>
            <a id="zoomInButton" class="btn btn-outline-secondary btn-circle"><i class="fa fa-plus" aria-hidden="true"></i></a>
        </div>
    </div>
</div>

   
{% endblock content %}

{% block script %}

    <!-- <script>
        $(document).ready(function() {
            var width = document.getElementById('page_template').offsetWidth;
            document.getElementById('content').style.width = width + 'px';
        });
    </script> -->

    <script>
        var zoom = 0.8;
        var zoomStep = 0.2;

        document.getElementById("zoomInButton").addEventListener("click", function() {
            if (zoom < 1) {
                zoom += zoomStep;

                var editor = document.getElementById("editor");
                var content = document.getElementById("content");

                editor.style.transform = "scale(" + zoom + ")";
                // content.style.height = (editor.getBoundingClientRect().height + 100) + "px";
            }
        });

        document.getElementById("zoomOutButton").addEventListener("click", function() {
            if (zoom > zoomStep + 0.01) {
                zoom -= zoomStep;

                var editor = document.getElementById("editor");
                var content = document.getElementById("content");


                editor.style.transform = "scale(" + zoom + ")";
                // content.style.height = (editor.getBoundingClientRect().height + 100) + "px";

            }
        });
    </script>

    <script>
        $(function() {

            var size = document.getElementById("page_template").getAttribute("size");
            var content_height = 0; // the height of the content, discluding the header/footer

            switch(size) {
                case "broadsheet":
                    content_height = 2680;
                    break;
                case "berliner":
                    content_height = 1620;
                    break;
                case "tabloid":
                    content_height = 1490;
                    break;
                default:
                    content_height = 0;
                    break;
            }

            // 1620 - berliner
            // 2680 - broadsheet
            // 1490 - tabloid

            var page = 1; // the beginning page number to show in the footer
            function buildNewsletter() {

                if ($('#newsletterContent').contents().length > 0) {
                    // when we need to add a new page, use a jq object for a template
                    // or use a long HTML string, whatever your preference
                    $page = $("#page_template").clone().addClass("page").css("display", "block");

                    // fun stuff, like adding page numbers to the footer
                    $page.find(".footer span").append(page);
                    $("#editor").append($page);
                    page++;

                    // here is the columnizer magic
                    $('#newsletterContent').columnize({
                        columns: '{{ object.columns }}',
                        target: ".page:last .content",
                        overflow: {
                            height: content_height,
                            id: "#newsletterContent",
                            doneFunc: function() {
                                console.log("done with page");
                                buildNewsletter();
                            }
                        }
                    });
                }
                $('#loading').hide();
                $('#editor').css("visibility", "visible");
            }

            setTimeout(buildNewsletter, 1000);
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>

    <script>
        
        document.addEventListener('DOMContentLoaded', (event) => {

            var dragSrcEl = null;

            function handleDragStart(e) {
                // this.style.opacity = '0.4';
                
                dragSrcEl = this;

                e.dataTransfer.effectAllowed = 'move';
                e.dataTransfer.setData('text/html', this.innerHTML);
            }

            function handleDragOver(e) {
                if (e.preventDefault) {
                    e.preventDefault();
                }

                e.dataTransfer.dropEffect = 'move';
                
                return false;
            }

            function handleDragEnter(e) {
                this.classList.add('over');
            }

            function handleDragLeave(e) {
                this.classList.remove('over');
            }

            function handleDrop(e) {
                if (e.stopPropagation) {
                    e.stopPropagation(); // stops the browser from redirecting.
                }
                
                if (dragSrcEl != this) {
                    dragSrcEl.innerHTML = this.innerHTML;
                    this.innerHTML = e.dataTransfer.getData('text/html');
                }

                var items = Array.prototype.slice.call(document.getElementById('homeSubmenu').children);
                var orders = {};
                    
                for (var i = 0; i < items.length; i++) {
                    orders[items[i].querySelector('#article-id').innerHTML] = items.indexOf(items[i]);
                }

                console.log(orders);

                $.ajax({
                    type: "POST",
                    url: "{% url 'app:article-order-update' %}",
                    data: {
                        'orders': JSON.stringify(orders),
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    success: function () {
                        console.log($(document.getElementById(e.target.parentElement.querySelector('#article-id').innerHTML)).index())
                    }
                });
                
                orders = {};

                $('#reload-btn').removeClass('btn-outline-secondary').addClass('btn-info ');


                return false;
            }

            function handleDragEnd(e) {
                // this.style.opacity = '1';  
            
                items.forEach(function (item) {
                    item.classList.remove('over');
                });
            }


                let items = document.querySelectorAll('.articles .article-item');
                items.forEach(function(item) {
                    item.addEventListener('dragstart', handleDragStart, false);
                    item.addEventListener('dragenter', handleDragEnter, false);
                    item.addEventListener('dragover', handleDragOver, false);
                    item.addEventListener('dragleave', handleDragLeave, false);
                    item.addEventListener('drop', handleDrop, false);
                    item.addEventListener('dragend', handleDragEnd, false);
                });
            });

    </script>

{% endblock script %}

app/templates/app/index.html
{% extends "app/base.html" %}
{% load static %}

{% block extra_head %}
<link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock extra_head %}

{% block content %}

    <div class="h-100 container">

        <!-- Header - where newspaper editor placed -->
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-center align-items-center">
                <a class="blog-header-logo text-dark" href="{% url 'app:index' %}">Newspaper Editor</a>
            </div>
        </header>


        <!-- Buttons of header -->
        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-center">
            
            {% if user.is_authenticated %}
                <a class="p-2 text-muted" href="{% url 'profile' %}">Profile</a>
                <a class="p-2 text-muted" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="p-2 text-muted" href="{% url 'login' %}">Login</a>
            {% endif %}

            <a class="p-2 text-muted" href="{% url 'register' %}">Sign Up</a>
            </nav>
        </div>


        <!-- Text with brief desription of application -->
        <main role="main" class="container" style="padding: 10%;">
            <h2>Create your own newspaper.</h2>
            <p class="lead mb-5">
                Newspaper Editor is an easy-to-use app for building simple and beautiful newspapers. 
                Just add your predefined articles and they would automatically transform into newspaper.
            </p>
            <h3 class="lead mb-3">
                This is a list of things we can do at the moment:
            </h3>
            <p class="lead">Fully-featured user profile</p>
            <p class="lead">Create, delete and edit Newspapers</p>
            <p class="lead">Add articles</p>
            <p class="lead">Newspaper page scaling</p>
            <p class="lead">Table of contents</p>
        </main>

        
        <!-- Footer with credentials -->
        <div class="row justify-content-center">
            <footer class="footer">
                <p class="mb-0">Newspaper editor app made for NSU Software Development course</p>
                <p class="mb-0">Created by Aleksandr Ushaev and Vladislav Nikiforov</p>
            </footer>
        </div>

    </div>

{% endblock content %}